name = input()
sid = int(input())
chinese = int(input())
cs = int(input())
pd= int(input())
total=(chinese+cs+pd)
print("Name:"+name)
print("ID:"+str(sid))
print("Average:"+str(total//3))
print("Total:"+str(total))